POST http://localhost:18545
Content-Type: application/json

{
  "method": "debug_traceTransaction",
  "params": [
    "0x8f9f62b8d04cca19df343e42268f2c1d095df488c05d8d1a80812e4bd7f0e5e2",
    {"tracer": "callTracer"}
  ],
  "id":1,
  "jsonrpc":"2.0"
}
